name: build and release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                arch: [x64]

        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: setup dotnet 9
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            - name: publish app
              shell: bash
              run: |
                  if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
                    RID="win-x64"
                  elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
                    RID="linux-x64"
                  else
                    RID="osx-x64"
                  fi
                  echo "Publishing for RID=$RID"
                  dotnet publish ./CEE.csproj -c Release -p:RuntimeIdentifier=$RID -p:SelfContained=true -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -o ./publish/${{ matrix.os }}

            - name: zip published files (windows)
              if: matrix.os == 'windows-latest'
              shell: powershell
              run: Compress-Archive -Path ./publish/windows-latest/* -DestinationPath ./cee-win-x64.zip -Force

            - name: zip published files (linux & macos)
              if: matrix.os != 'windows-latest'
              shell: bash
              run: |
                  if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
                    RID="linux-x64"
                  else
                    RID="osx-x64"
                  fi
                  cd ./publish/${{ matrix.os }}
                  zip -r ../../cee-${RID}.zip .

            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: cee-${{ matrix.os == 'windows-latest' && 'win-x64' || matrix.os == 'ubuntu-latest' && 'linux-x64' || 'osx-x64' }}
                  path: ./cee-*.zip

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: download artifacts
              uses: actions/download-artifact@v4
              with:
                  path: ./artifacts

            - name: install gh cli
              run: |
                  sudo apt update
                  sudo apt install -y gh

            - name: upload release assets
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  for file in ./artifacts/*.zip; do
                    gh release upload ${{ github.ref_name }} "$file" --clobber
                  done
