name: build and release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                arch: [x64]

        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: setup dotnet 9
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            - name: publish app
              run: dotnet publish -c Release -r ${{ matrix.os == 'windows-latest' && 'win-x64' || matrix.os == 'ubuntu-latest' && 'linux-x64' || matrix.os == 'macos-latest' && 'osx-x64' }} --self-contained true /p:PublishSingleFile=true /p:Version=${{ github.ref_name }} -o ./publish/${{ matrix.os }}

            - name: zip publish folder
              run: |
                  cd publish
                  zip -r ../${{ matrix.os }}-x64-${{ github.ref_name }}.zip ./${{ matrix.os }}
              shell: bash

            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.os }}-x64-${{ github.ref_name }}.zip
                  path: ./${{ matrix.os }}-x64-${{ github.ref_name }}.zip

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: download artifacts
              uses: actions/download-artifact@v4
              with:
                  path: ./artifacts

            - name: install gh cli
              run: |
                  sudo apt update
                  sudo apt install -y gh

            - name: create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: Release ${{ github.ref_name }}
                  draft: false
                  prerelease: false

            - name: upload release assets
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  for file in ./artifacts/*.zip; do
                    gh release upload ${{ github.ref_name }} "$file"
                  done
